apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations: {}
  labels:
    app: productpage
    app.kubernetes.io/component: productpage
    app.kubernetes.io/instance: productpage
  name: productpage
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: productpage:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: migrating-apps-v3/1.1
      uri: https://github.com/rh-tstockwell/bookinfo-productpage.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: python:3.6
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: Rec7BdnfT3IRn-IN20TP
    type: GitHub
  - generic:
      secret: aSXigryMiIpBvhPK5hRT
    type: Generic
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
