apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations: {}
  labels:
    app: productpage
    app.kubernetes.io/component: productpage
    app.kubernetes.io/instance: productpage
  name: productpage
spec:
  lookupPolicy:
    local: false
