apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  labels:
    app: productpage
    app.kubernetes.io/component: productpage
    app.kubernetes.io/instance: productpage
  name: productpage
spec:
  port:
    targetPort: 8080-tcp
  subdomain: ""
  to:
    kind: Service
    name: productpage
    weight: 100
  wildcardPolicy: None
