apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: productpage
    app.kubernetes.io/component: productpage
    app.kubernetes.io/instance: productpage
  name: productpage
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deploymentconfig: productpage
  sessionAffinity: None
  type: ClusterIP
